run_name: dlinear
seed: 16
context_length: 168
prediction_length: 24
stride: 24
max_epochs: 500
batch_size: 256
learning_rate: 0.001
early_stopping_patience: 15
early_stopping_min_delta: 0.0001
model:
  type: dlinear
  moving_average: 25

